title: Shrink Your PowerPoint Slides
description: >- # this means to ignore newlines until "baseurl:"
  Making PowerPoint slides a little smaller
twitter_username: lyledodge
github_username: lyledodgegh

# Build settings
theme: jekyll-theme-slate