title: Shrink Your PowerPoint Slides
description: >- # this means to ignore newlines until "baseurl:"
  Shrink Your PowerPoint Slides
twitter_username: lyledodge
github_username: lyledodgegh

# Build settings
theme: jekyll-theme-leap-day